config/routes.rb
Rails.application.routes.draw do
  root 'pages/tops#show'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :pages do
    resource :top, only: :show
  end

  resource :sandbox, only: :show
  resources :teams, param: :name, only: :index do
    resources :posts, param: :number
  end

  get '/auth/:provider/callback' => 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member
  include Her::Model
  include ActiveModel::Serialization

  parse_root_in_json true, format: :active_model_serializers

  belongs_to :team
end

app/models/post.rb
class Post
  include Her::Model
  include ActiveModel::Serialization

  parse_root_in_json true, format: :active_model_serializers
  collection_path 'teams/:team_name/posts'
  primary_key :number

  belongs_to :team
end

app/models/stat.rb
class Stat
  include Her::Model
  include ActiveModel::Serialization

  belongs_to :team
end

app/models/team.rb
class Team
  include Her::Model

  primary_key :name
  parse_root_in_json true, format: :active_model_serializers

  has_many :posts, dependent: :destroy
  has_many :members, dependent: :destroy
  has_one :stats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: %i[esa]

  def self.from_omniauth(auth)
    user = find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    user.nickname = auth.info.nickname
    user.image_url = auth.info.image
    user.token = auth.credentials.token
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  before_action :initialize_her

  def new_session_path(_scope)
    new_user_session_path
  end

  private

  def initialize_her
    return unless user_signed_in?

    Her::API.setup url: 'https://api.esa.io/v1' do |c|
      # Request
      c.use FaradayMiddleware::OAuth2, current_user.token, token_type: :bearer
      c.use Faraday::Request::UrlEncoded

      # Response
      c.use Her::Middleware::DefaultParseJSON

      c.use FaradayMiddleware::Instrumentation
      c.use Faraday::Response::Logger

      # Adapter
      c.use Faraday::Adapter::NetHttp
    end
  end
end

app/controllers/pages/tops_controller.rb
module Pages
  class TopsController < ApplicationController
    def show; end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_team
  before_action :set_post, only: %i[show edit destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @team.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    render json: @post
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post: post_params, _team_name: @team.name)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if Post.save_existing(params[:number], post: post_params, _team_name: @team.name)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render json: { message: 'ok' }, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_team
    @team = Team.find(params[:team_name])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = @team.posts.find(params[:number])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.fetch(:post, {}).permit(:name, :body_md).to_h
  end
end

app/controllers/sandboxes_controller.rb
class SandboxesController < ApplicationController
  def show; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    session[:token] = request.env['omniauth.auth'][:credentials][:token]
    redirect_to '/', notice: 'ログインしました'
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def index
    @teams = Team.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def esa
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'esa') if is_navigational_format?
      else
        session['devise.esa_data'] = request.env['omniauth.auth']
        redirect_to root_path
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webpack_bundle_helper.rb
module WebpackBundleHelper
  class BundleNotFound < StandardError; end

  def asset_bundle_path(entry, **options)
    raise BundleNotFound, "Could not find bundle with name #{entry}" unless manifest.key? entry
    asset_path(bundle_host + manifest.fetch(entry), **options)
  end

  def javascript_bundle_tag(entry, **options)
    path = asset_bundle_path("#{entry}.js")

    options = {
      src: path,
      defer: true
    }.merge(options)

    # async と defer を両方指定した場合、ふつうは async が優先されるが、
    # defer しか対応してない古いブラウザの挙動を考えるのが面倒なので、両方指定は防いでおく
    options.delete(:defer) if options[:async]

    javascript_include_tag '', **options
  end

  def stylesheet_bundle_tag(entry, **options)
    path = asset_bundle_path("#{entry}.css")

    options = {
      href: path
    }.merge(options)

    stylesheet_link_tag '', **options
  end

  # image_bundle_tag の場合は、entry はちゃんと拡張子付きで書いて欲しい
  def image_bundle_tag(entry, **options)
    raise ArgumentError, "Extname is missing with #{entry}" if File.extname(entry).blank?
    image_tag asset_bundle_path(entry), **options
  end

  private

  MANIFEST_PATH = 'public/packs/manifest.json'.freeze

  def manifest
    @manifest ||= JSON.parse(File.read(MANIFEST_PATH))
  end

  def bundle_host
    Rails.env.development? ? 'http://localhost:8080' : ''
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Esabako</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_bundle_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_bundle_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <%= link_to 'esabako', root_path, class: 'navbar-brand' %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <% unless user_signed_in? %>
            <%= link_to 'Login', user_esa_omniauth_authorize_path, class: 'nav-link' %>
          <% else %>
            <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/tops/show.html.erb
<h1>Pages::Tops#show</h1>
<p>Find me in app/views/pages/tops/show.html.erb</p>

app/views/posts/_form.html.erb
<div rel="esa-editor" team-name="<%= team.name %>" post-number="<%= post&.number %>"></div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', team: @team, post: @post %>

<%= link_to 'Show', [@team, @post] %> |
<%= link_to 'Back', team_posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= link_to 'New Post', new_team_post_path(@team) %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.name, edit_team_post_path(@team, post) %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', team: @team, post: nil %>

<%= link_to 'Back', team_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<dl>
  <dt><%= t 'activemodel.post.name' %></dt>
  <dd><%= @post.name %></dd>
  <dt><%= t 'activemodel.post.body' %></dt>
  <dd><%== @post.body_html %></dd>
</dl>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/sandboxes/show.html.erb
<div id="editor">
# アイウエオ

- かきくけこ
</div>